AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-authorizer
  SAM Template for lambda-authorizer

Globals:
  Function:
    Timeout: 500
    MemorySize: 128
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        DEFAULT_DB_NAME: !Ref Table
        REGION_NAME: !Ref Region
Parameters:
  Table:
    Type: String
    Default: DefaultDB
  Region:
    Type: String
    Default: ap-south-1

Resources:
  ListAllEntriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/
      Handler: app.listAllEntries
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DefaultDBTable
      Events:
        CreateStudent:
          Type: Api
          Properties:
            Path: /other
            Method: get

  DefaultDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref Table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
